version: '3.8'

services:
  webapp:
    build:
      context: ./webapp
    container_name: andres_webapp
    restart: always
    environment:
      - FLASK_APP=/app/webapp/run.py
      - FLASK_ENV=production
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=myflaskapp
    volumes:
      - ./webapp:/app/webapp
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - webnet

  nginx:
    image: nginx:1.27.2
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/certificate.crt:/etc/ssl/nginx/certificate.crt"
      - "./nginx/private.key:/etc/ssl/nginx/private.key"
    depends_on:
      - webapp
    networks:
      - webnet

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myflaskapp
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data: